import os
import glob
from huggingface_hub import HfApi, create_repo, upload_folder, get_token
from datetime import datetime
from dotenv import load_dotenv
# === LOAD .env ===
load_dotenv()


import os
import glob
from huggingface_hub import HfApi, create_repo, upload_folder, get_token
from datetime import datetime


# === CONFIGURATION ===
HF_REPO = os.environ.get("HF_REPO", "ShreyashDhoot/policy-tuned-inpainter")

# Resolve paths relative to the script file, not CWD
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
EVAL_DIR = os.path.join(PROJECT_ROOT, "eval_outputs")
MODEL_CARD = os.path.join(PROJECT_ROOT, "README.md")


# === AUTH ===
api = HfApi()
if not get_token():
    raise RuntimeError(
        "No HuggingFace token found. Run `huggingface-cli login` or set HF_TOKEN."
    )


# === CREATE REPO IF NEEDED ===
if not api.repo_exists(HF_REPO, repo_type="model"):
    print(f"Creating repo {HF_REPO}...")
    create_repo(HF_REPO, repo_type="model", exist_ok=True)


# === GATHER CHECKPOINTS AND EVAL OUTPUTS ===
ckpt_folders = sorted([
    f for f in glob.glob(os.path.join(PROJECT_ROOT, "checkpoint--*"))
    if os.path.isdir(f)
])
eval_imgs = sorted(glob.glob(os.path.join(EVAL_DIR, "eval_step*_sample*.png")))

print(f"Found {len(ckpt_folders)} checkpoint(s): {[os.path.basename(c) for c in ckpt_folders]}")
print(f"Found {len(eval_imgs)} eval image(s)")

if not ckpt_folders:
    print("WARNING: No checkpoint-- directories found in project root. Skipping checkpoint upload.")


# === GENERATE MODEL CARD ===
def make_model_card(ckpt_folders, eval_imgs, out_path):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Valid YAML frontmatter — base_model must be a Hub ID, NOT a local path
    frontmatter = """\
---
base_model: runwayml/stable-diffusion-inpainting
tags:
  - stable-diffusion
  - inpainting
  - lora
  - kto
  - diffusers
license: creativeml-openrail-m
library_name: diffusers
pipeline_tag: image-to-image
---
"""

    lines = [
        frontmatter,
        f"# {HF_REPO}",
        "",
        f"**Last updated:** {now}",
        "",
        "## Model Description",
        "",
        "KTO fine-tuned Stable Diffusion inpainter with LoRA for safety alignment.",
        "Base model: [`runwayml/stable-diffusion-inpainting`](https://huggingface.co/runwayml/stable-diffusion-inpainting)",
        "",
        "## Checkpoints",
        "",
    ]

    if ckpt_folders:
        for ckpt in ckpt_folders:
            lines.append(f"- `{os.path.basename(ckpt)}`")
    else:
        lines.append("_No checkpoints available._")

    lines.append("")
    lines.append("## Example Eval Outputs")
    lines.append("")

    if eval_imgs:
        for img in eval_imgs[:8]:
            lines.append(f"![{os.path.basename(img)}](eval_outputs/{os.path.basename(img)})")
    else:
        lines.append("_No eval images available._")

    lines.append("")
    lines.append("---")
    lines.append("_Auto-generated by push_to_hf.py_")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Model card written to {out_path}")


make_model_card(ckpt_folders, eval_imgs, MODEL_CARD)


# === UPLOAD CHECKPOINTS ===
for ckpt in ckpt_folders:
    ckpt_name = os.path.basename(ckpt)
    print(f"Uploading {ckpt_name} ...")
    upload_folder(
        repo_id=HF_REPO,
        folder_path=ckpt,
        repo_type="model",
        path_in_repo=f"checkpoints/{ckpt_name}",
        ignore_patterns=[
            "*.pt",        # skip full weight tensors; keep LoRA/adapter files
            "README.md",   # skip trainer-generated README with local base_model path
        ],
    )
    print(f"  ✓ {ckpt_name} uploaded.")


# === UPLOAD EVAL OUTPUTS ===
if os.path.isdir(EVAL_DIR):
    print(f"Uploading eval outputs from {EVAL_DIR} ...")
    upload_folder(
        repo_id=HF_REPO,
        folder_path=EVAL_DIR,
        repo_type="model",
        path_in_repo="eval_outputs",
    )
    print("  ✓ Eval outputs uploaded.")
else:
    print(f"Skipping eval outputs — {EVAL_DIR} does not exist.")


# === UPLOAD MODEL CARD (our clean README, not the trainer's) ===
print("Uploading README.md ...")
api.upload_file(
    path_or_fileobj=MODEL_CARD,
    path_in_repo="README.md",
    repo_id=HF_REPO,
    repo_type="model",
)
print("  ✓ README.md uploaded.")


print(f"\nDone! View your model at https://huggingface.co/{HF_REPO}")